version: "3.3"

services:
  bootstrap-node:
    image: app
    build:
      context: ./../
      dockerfile: infra/Dockerfile
    environment:
      IS_BOOTSTRAP: 'true'
      FLASK_ENV: development
      MAX_USER_COUNT: ${MAX_USER_COUNT}
      BLOCK_CAPACITY: ${BLOCK_CAPACITY}
      MINING_DIFFICULTY: ${MINING_DIFFICULTY}
      ENV: ${ENV}
    ports:
      - "5000:5000/tcp"

  p2p-node:
    image: app
    build:
      context: ./../
      dockerfile: infra/Dockerfile
    environment:
      BOOTSTRAP_HOST: ${BOOTSTRAP_HOST}
      BOOTSTRAP_PORT: ${BOOTSTRAP_PORT}
      FLASK_ENV: development
      MAX_USER_COUNT: ${MAX_USER_COUNT}
      BLOCK_CAPACITY: ${BLOCK_CAPACITY}
      MINING_DIFFICULTY: ${MINING_DIFFICULTY}
      ENV: ${ENV}
    deploy:
      replicas: 2
    ports:
      - "6000-6002:5000/tcp"
    depends_on:
      - bootstrap-node
